name: reading_pace_app
description: Reading pace tracker app with timer and page logging.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image: ^4.5.4
  image_picker: ^1.1.2
  image_gallery_saver_plus: ^4.0.1
  sentry_flutter: ^8.14.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/app_icon.png
    background_color: "#ffffff"
    theme_color: "#E60023"
  windows:
    generate: true
    image_path: assets/app_icon.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/record_background.jpg
